name: Code Analysis

on:
  push:
    branches: [stage]

permissions:
  contents: write

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
      - run: composer install --no-progress --prefer-dist --no-dev
      - run: composer require phpstan/phpstan --no-progress --no-scripts
      - run: vendor/bin/phpstan analyse src
      - run: composer remove phpstan/phpstan --no-progress --no-scripts

  pint:
    name: Pint AutoFix
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
      - run: composer install --no-progress --prefer-dist --no-dev
      - run: composer require laravel/pint --no-progress --no-scripts
      - run: vendor/bin/pint --verbose

      - name: Check pint changes
        run: |
          git status
          git diff

      - name: Commit and push style fixes
        run: |
          git config --global user.name "pint[bot]"
          git config --global user.email "pint@github-actions"
          git add -A
          git diff --cached --quiet && echo "✅ no commit" || \
          (git commit -m "style: auto-fix with Pint" && git push origin stage)

      - run: composer remove laravel/pint --no-progress --no-scripts

  auto-merge:
    name: Auto merge to main
    runs-on: ubuntu-latest
    needs: [phpstan, pint]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge stage → main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git checkout -B main origin/main
          git merge origin/stage --allow-unrelated-histories -X theirs -m "chore: auto-merge stage into main"
          git push origin main
